NAME=proj5

all:
	pdflatex $(NAME).tex

clean:
	rm -f $(NAME).aux $(NAME).log $(NAME).dvi $(NAME).ps $(NAME).out $(NAME).toc $(NAME).snm $(NAME).nav $(NAME).pdf 


zip:	
	zip xorsak02-fit.zip $(NAME).tex Makefile FredericGoudy.jpg William-Addison-Dwiggins.jpg

unzip:
	unzip xorsak02-fit